### ISSUE TITLE
`./scripts/create-database-tables-local.sh` terminates with a `psql: error: ./data/import-csvs.sql: No such file or directory`

### ISSUE THREAD

**Issue by MaxwellBo** [gatho-party/gatho-website#7]
Noting that

```
~/gatho-website > ls data
create-auth-db.sql  schema.sql
```

Is this WAI? Perhaps a file was not committed?

**Comment by jakecoppinger** [comment]
Just pushed a commit that fixes this - I previously populated the DB with some fake data on initialisation but decided it'd be more maintainable without that. Removed the `csv` import!
